In [63]:
import pandas as pd
import string
import re

In [64]:
df=pd.read_csv(r'C:/email_spam_classifier/data/emails.csv')

In [65]:
sample_text = df['Text'].iloc[10]

print(sample_text)

Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line .

# convert to lowercase

In [66]:
def lowercase_text(text):
    return text.lower()

In [67]:
lowercase_text(sample_text)

"subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line . "

# Remove punctuation

In [68]:
def remove_punctuations(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [69]:
text = "Congratulations!!! You won $1000!!!"

print("Original:")
print(text)

print("\nAfter punctuation removal:")
print(remove_punctuations(text))

Original:
Congratulations!!! You won $1000!!!

After punctuation removal:
Congratulations You won 1000

In [70]:
remove_punctuations(sample_text)

'Subject las vegas high rise boom  las vegas is fast becoming a major metropolitan city  60   new high rise towers are expected to be built on and around the las vegas strip  within the next 3  4 years  that  s 30  000  condominiums   this boom has just begun  buy first    early phase   pre  construction pricing is now available on las vegas high rises including  trump  cosmopolitan  mgm  turnberry  icon  sky  among others   join the interest list   http    www  verticallv  com  message has been sent to you by realty one highrise  learn more at www  verticallv  comif you  wish to be excluded from future mailings  please reply with the word remove in  the subject line  '

# remove number

In [71]:
def remove_numbers(text):
    return re.sub(r'\d+','',text)

In [72]:
text = "You won $5000! Call 9876543210."

print("Original:")
print(text)

print("\nNumbers removed:")
print(remove_numbers(text))

Original:
You won $5000! Call 9876543210.

Numbers removed:
You won $! Call .

In [73]:
remove_numbers(sample_text)

"Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city !  +  new high rise towers are expected to be built on and around the las vegas strip  within the next  -  years , that ' s  ,  + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line . "

# remove urls

In [74]:
def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

In [75]:
text = "Congratulations! Visit https://example.com/claim now!"

print("Original:")
print(text)

print("\nURLs removed:")
print(remove_urls(text))

Original:
Congratulations! Visit https://example.com/claim now!

URLs removed:
Congratulations! Visit  now!

In [76]:
def replace_urls(text):
        return re.sub(
            r'https?://\S+|www\.\S+',
            'URL_TOKEN',
            text
        )

In [77]:
text = "Congratulations! Visit https://example.com/claim now!"

print(replace_urls(text))

Congratulations! Visit URL_TOKEN now!

In [78]:
text = "FREE prize! Click https://example.com/win now!"

print("ORIGINAL:")
print(text)

print("\nURL REMOVED:")
print(remove_urls(text))

print("\nURL REPLACED:")
print(replace_urls(text))

ORIGINAL:
FREE prize! Click https://example.com/win now!

URL REMOVED:
FREE prize! Click  now!

URL REPLACED:
FREE prize! Click URL_TOKEN now!

In [79]:
test_text = """
Visit https://example.com
Visit http://example.com
Visit www.example.com
Visit example.com
"""

print(replace_urls(test_text))

Visit URL_TOKEN
Visit URL_TOKEN
Visit URL_TOKEN
Visit example.com

In [80]:
url_pattern=r'https?://\S+|www\.\S+'

In [81]:
url_count=df['Text'].str.contains(
    url_pattern,
    regex=True,
    case=False,
    na=False
).sum()

In [82]:
print("Messages containing URLs:", url_count)

Messages containing URLs: 0

In [83]:
print(
    "Percentage:",
    url_count / len(df) * 100
)

Percentage: 0.0

In [84]:
print(df['Text'].str.contains('@', regex=False, na=False).sum())

2851

In [85]:
print(df['Text'].iloc[0])

Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

In [86]:
print(
    df['Text'].str.contains(
        'http|www|\.com|\.org|\.net',
        case=False,
        na=False,
        regex=True
    ).sum()
)

1151

In [87]:
print(df['Text'].str.contains('@', regex=False, na=False).sum())

2851

In [88]:
url_like=df[
    df['Text'].str.contains(
        r'http|www|\.com|\.org|\.net',
        case=False,
        na=False,
        regex=True
    )
]

In [89]:
display(url_like[['Text', 'Spam']].head(10))

                                                 Text  Spam
10  Subject: las vegas high rise boom  las vegas i...     1
21  Subject: re : wearable electronics  hi my name...     1
25  Subject: guzzle like a fountain  spur m rocks ...     1
31  Subject: [ ilug ] seeking your partnership  de...     1
32  Subject: [ ilug ] guaranteed to lose 10 - 12 l...     1
35  Subject: failure notice  hi . this is the qmai...     1
38  Subject: branded softs  roxio easy media creat...     1
39  Subject: extra time - last 5 - 10 times longer...     1
41  Subject: bro check out this awesome new produc...     1
44  Subject: wish you could be better ?  penis gro...     1

In [90]:
url_like['Spam'].value_counts()

Spam
0    719
1    432
Name: count, dtype: int64

In [91]:
url_like['Spam'].value_counts(normalize=True) * 100

Spam
0    62.46742
1    37.53258
Name: proportion, dtype: float64

In [92]:
email_like = df[
    df['Text'].str.contains('@', regex=False, na=False)
]

display(email_like[['Text', 'Spam']].head(10))

                                                 Text  Spam
3   Subject: 4 color printing special  request add...     1
8   Subject: undeliverable : home based business f...     1
15  Subject: search engine position  be the very f...     1
20  Subject: any med for your girl to be happy !  ...     1
31  Subject: [ ilug ] seeking your partnership  de...     1
32  Subject: [ ilug ] guaranteed to lose 10 - 12 l...     1
33  Subject: re : just to her . . .  mdaemon has i...     1
35  Subject: failure notice  hi . this is the qmai...     1
45  Subject: 1000 full color brochures 335  the ts...     1
47  Subject: failure notice  hi . this is the qmai...     1

In [93]:
email_like['Spam'].value_counts()

Spam
0    2572
1     279
Name: count, dtype: int64

In [94]:
email_pattern = r'\b[\w.-]+@[\w.-]+\.\w+\b'

In [95]:
email_count = df['Text'].str.contains(
    email_pattern,
    regex=True,
    case=False,
    na=False
).sum()

print("Messages containing email addresses:", email_count)

Messages containing email addresses: 0

In [96]:
email_messages = df[
    df['Text'].str.contains(
        email_pattern,
        regex=True,
        case=False,
        na=False
    )
]

print(email_messages['Spam'].value_counts())

Series([], Name: count, dtype: int64)

In [97]:
test_email = "Contact john@example.com or admin@test.org"

print(re.findall(email_pattern, test_email))

['john@example.com', 'admin@test.org']

In [98]:
email_messages = df[
    df['Text'].str.contains(
        email_pattern,
        regex=True,
        case=False,
        na=False
    )
]

print("Messages containing email addresses:", len(email_messages))
print(email_messages['Spam'].value_counts())

Messages containing email addresses: 0
Series([], Name: count, dtype: int64)

In [99]:
email_at = df[df['Text'].str.contains('@', regex=False, na=False)]

display(email_at[['Text', 'Spam']].head(10))

                                                 Text  Spam
3   Subject: 4 color printing special  request add...     1
8   Subject: undeliverable : home based business f...     1
15  Subject: search engine position  be the very f...     1
20  Subject: any med for your girl to be happy !  ...     1
31  Subject: [ ilug ] seeking your partnership  de...     1
32  Subject: [ ilug ] guaranteed to lose 10 - 12 l...     1
33  Subject: re : just to her . . .  mdaemon has i...     1
35  Subject: failure notice  hi . this is the qmai...     1
45  Subject: 1000 full color brochures 335  the ts...     1
47  Subject: failure notice  hi . this is the qmai...     1

In [100]:
for text in email_at['Text'].head(10):
    position = text.find('@')
    print(text[max(0, position-50):position+80])
    print("-" * 80)

- 8090 fax : ( 626 ) 338 - 8102 e - mail : ramsey @ goldengraphix . com  request additional information now ! click here  click he
--------------------------------------------------------------------------------
did not reach the following recipient ( s ) :  75 @ tfi . kpn . com on mon , 25 feb 2002 13 : 32 : 23 + 0100  the recipient name i
--------------------------------------------------------------------------------
o find out if you qualify via email at  searchl 1 @ telefonica . net . pe it ' s very important to include the url ( s ) if you  a
--------------------------------------------------------------------------------
to choose from a great variety of llcensed love t @ bs ! best pri $ es , fast shippinq and guaranteed effect ! here you buy it riq
--------------------------------------------------------------------------------
. eseimoku  - -  irish linux users ' group : ilug @ linux . ie  http : / / www . linux . ie / mailman / listinfo / ilug for ( un )
--------------------------------------------------------------------------------
nk below .  - -  irish linux users ' group : ilug @ linux . ie  http : / / www . linux . ie / mailman / listinfo / ilug for ( un )
--------------------------------------------------------------------------------
t will not be delivered .  from : projecthoneypot @ projecthoneypot . org  to : s . denham @ capitalspreads . com  subject : * * *
--------------------------------------------------------------------------------
( squirrelmail authenticated user projecthoneypot @ projecthoneypot . org ) ;  by mailwisconsin . com with http id j 87 gzo 248158
--------------------------------------------------------------------------------
14 . 443 . 0908 phone  214 . 443 . 0308 fax  info @ wileyprint . com  note : this is the first and last time wiley print will ever
--------------------------------------------------------------------------------
0 : 58 : 51 - 0000  delivered - to : nic - notify @ internetcds . com  received : ( qmail 50352 invoked from network ) ; 19 jul 20
--------------------------------------------------------------------------------

In [101]:
print("Contains @ :", df['Text'].str.contains('@', regex=False, na=False).sum())

print(
    "Contains @ followed by text:",
    df['Text'].str.contains(r'@\w+', regex=True, na=False).sum()
)

print(
    "Contains @ with a dot later:",
    df['Text'].str.contains(r'@\S+\.', regex=True, na=False).sum()
)

Contains @ : 2851
Contains @ followed by text: 0
Contains @ with a dot later: 0

In [102]:
email_pattern = r'\b[\w.-]+\s*@\s*[\w.-]+(?:\s*\.\s*[\w.-]+)+\b'

In [103]:
test_email = """
ramsey @ goldengraphix . com
75 @ tfi . kpn . com
projecthoneypot @ projecthoneypot . org
"""

print(re.findall(email_pattern, test_email))

['ramsey @ goldengraphix . com', '75 @ tfi . kpn . com', 'projecthoneypot @ projecthoneypot . org']

In [104]:
email_count = df['Text'].str.contains(
    email_pattern,
    regex=True,
    case=False,
    na=False
).sum()

print("Messages containing email addresses:", email_count)

Messages containing email addresses: 1815

In [105]:
email_messages = df[
    df['Text'].str.contains(
        email_pattern,
        regex=True,
        case=False,
        na=False
    )
]

print(email_messages['Spam'].value_counts())

Spam
0    1572
1     243
Name: count, dtype: int64

In [106]:
for text in email_messages['Text'].head(10):
    matches = re.findall(email_pattern, text)
    print(matches)
    print("-" * 60)

['ramsey @ goldengraphix . com']
------------------------------------------------------------
['75 @ tfi . kpn . com']
------------------------------------------------------------
['1 @ telefonica . net . pe', '6 @ speedy . com . pe']
------------------------------------------------------------
['ilug @ linux . ie', 'listmaster @ linux . ie']
------------------------------------------------------------
['ilug @ linux . ie', 'listmaster @ linux . ie']
------------------------------------------------------------
['projecthoneypot @ projecthoneypot . org', 'denham @ capitalspreads . com']
------------------------------------------------------------
['projecthoneypot @ projecthoneypot . org', 'info @ deboel . net']
------------------------------------------------------------
['info @ wileyprint . com']
------------------------------------------------------------
['notify @ internetcds . com', 'projecthoneypot @ projecthoneypot . org', 'notify @ internetcds . com']
------------------------------------------------------------
['hannah @ speedy . com . pe', 'hannah @ speedy . com . pe']
------------------------------------------------------------

In [107]:
def replace_email_addresses(text):
    return re.sub(
        email_pattern,
        'EMAIL_TOKEN',
        text
    )

In [108]:
text = """
Contact ramsey @ goldengraphix . com
or projecthoneypot @ projecthoneypot . org
for more information.
"""

print("Original:")
print(text)

print("\nAfter replacement:")
print(replace_email_addresses(text))

Original:

Contact ramsey @ goldengraphix . com
or projecthoneypot @ projecthoneypot . org
for more information.


After replacement:

Contact EMAIL_TOKEN
or EMAIL_TOKEN
for more information.

In [109]:
sample_email = email_messages['Text'].iloc[10]

print("ORIGINAL:\n")
print(sample_email)

print("\nAFTER EMAIL REPLACEMENT:\n")
print(replace_email_addresses(sample_email))

ORIGINAL:

Subject: yyyy , do you know the hgh differences ?  hello , jm @ netnoteinc . comhuman growth hormone therapy  lose weight while building lean muscle massand reversing the ravages of aging all at once .  remarkable discoveries about human growth hormones ( hgh ) are changing the way we think about aging and weight loss .  lose weightbuild muscle tonereverse aging  increased libidoduration of penile erectionhealthier bones  improved memoryimproved skinnew hair growthwrinkle disappearance visit  our web site and learn the facts : click hereyou are receiving this email as a subscr - in amerig lisve yoursts , just click here

AFTER EMAIL REPLACEMENT:

Subject: yyyy , do you know the hgh differences ?  hello , EMAIL_TOKEN growth hormone therapy  lose weight while building lean muscle massand reversing the ravages of aging all at once .  remarkable discoveries about human growth hormones ( hgh ) are changing the way we think about aging and weight loss .  lose weightbuild muscle tonereverse aging  increased libidoduration of penile erectionhealthier bones  improved memoryimproved skinnew hair growthwrinkle disappearance visit  our web site and learn the facts : click hereyou are receiving this email as a subscr - in amerig lisve yoursts , just click here

# Stopword Handling

In [110]:
import nltk

In [111]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kunal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [112]:
from nltk.corpus import stopwords

In [113]:
stop_words=set(stopwords.words('english'))

In [114]:
print("Number of stopwords:", len(stop_words))

Number of stopwords: 198

In [116]:
print(list(stop_words)[:20])

['d', "shouldn't", 'yourself', 'up', "didn't", "needn't", 'to', 'than', 'all', "mightn't", 'under', "they'll", "we're", "he'll", 'me', 'is', 'its', 'only', 'being', 'hadn']

In [117]:
def remove_stopwords(text):
    words = text.split()
    
    filtered_words = [
        word for word in words
        if word.lower() not in stop_words
    ]
    
    return ' '.join(filtered_words)

In [118]:
text = "This is a very good offer for you"

print("Original:")
print(text)

print("\nAfter stopword removal:")
print(remove_stopwords(text))

Original:
This is a very good offer for you

After stopword removal:
good offer

In [119]:
sample_text = df['Text'].iloc[0]

print("ORIGINAL:\n")
print(sample_text)

print("\nWITHOUT STOPWORDS:\n")
print(remove_stopwords(sample_text))

ORIGINAL:

Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

WITHOUT STOPWORDS:

Subject: naturally irresistible corporate identity lt really hard recollect company : market full suqgestions information isoverwhelminq ; good catchy logo , stylish statlonery outstanding website make task much easier . promise havinq ordered iogo company automaticaily become world ieader : isguite ciear without good products , effective business organization practicable aim hotat nowadays market ; promise marketing efforts become much effective . list clear benefits : creativeness : hand - made , original logos , specially done reflect distinctive company image . convenience : logo stationery provided formats ; easy - - use content management system letsyou change website content even structure . promptness : see logo drafts within three business days . affordability : marketing break - ' make gaps budget . 100 % satisfaction guaranteed : provide unlimited amount changes extra fees surethat love result collaboration . look portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

In [120]:
def count_stopwords(text):
    words = text.split()

    return sum(
        1 for word in words
        if word.lower() in stop_words
    )

In [121]:
df['stopword_count'] = df['Text'].apply(count_stopwords)

In [122]:
df.groupby('Spam')['stopword_count'].describe()

       count       mean         std  min   25%   50%    75%     max
Spam
0     4360.0  92.620872  116.403259  0.0  32.0  64.0  115.0  2878.0
1     1368.0  79.366228  155.776516  0.0  18.0  37.0   71.0  2464.0

In [123]:
df['word_count'] = df['Text'].apply(lambda x: len(x.split()))

df['stopword_ratio'] = (
    df['stopword_count'] / df['word_count']
)

In [124]:
df.groupby('Spam')['stopword_ratio'].describe()

       count      mean       std  min       25%       50%       75%       max
Spam
0     4360.0  0.279470  0.095345  0.0  0.212932  0.280945  0.347136  0.574468
1     1368.0  0.282528  0.106891  0.0  0.195122  0.295615  0.361351  0.530562

# Spacy

In [125]:
import spacy

In [126]:
nlp = spacy.load("en_core_web_sm")

In [127]:
def spacy_tokenize(text):
    doc = nlp(text)
    return [token.text for token in doc]

In [128]:
sample_text = "Congratulations! You have won a free prize."

tokens = spacy_tokenize(sample_text)

print(tokens)

['Congratulations', '!', 'You', 'have', 'won', 'a', 'free', 'prize', '.']

In [129]:
sample = df['Text'].iloc[0]

tokens = spacy_tokenize(sample)

print(tokens[:50])

['Subject', ':', 'naturally', 'irresistible', 'your', 'corporate', 'identity', ' ', 'lt', 'is', 'really', 'hard', 'to', 'recollect', 'a', 'company', ':', 'the', ' ', 'market', 'is', 'full', 'of', 'suqgestions', 'and', 'the', 'information', 'isoverwhelminq', ';', 'but', 'a', 'good', ' ', 'catchy', 'logo', ',', 'stylish', 'statlonery', 'and', 'outstanding', 'website', ' ', 'will', 'make', 'the', 'task', 'much', 'easier', '.', ' ']

In [130]:
df['spacy_token_count'] = df['Text'].apply(
    lambda x: len(spacy_tokenize(x))
)

       count        mean         std  min     25%    50%     75%     max
Spam
0     4360.0  380.666972  438.257743  3.0  132.75  265.0  484.00  8986.0
1     1368.0  289.792398  484.313556  6.0   90.00  155.0  277.25  6623.0

In [131]:
df.groupby('Spam')['spacy_token_count'].describe()

       count        mean         std  min     25%    50%     75%     max
Spam
0     4360.0  380.666972  438.257743  3.0  132.75  265.0  484.00  8986.0
1     1368.0  289.792398  484.313556  6.0   90.00  155.0  277.25  6623.0

In [132]:
print("Number of English stopwords:", len(stop_words))

print("\nIs 'not' a stopword?", "not" in stop_words)
print("Is 'no' a stopword?", "no" in stop_words)
print("Is 'never' a stopword?", "never" in stop_words)

Number of English stopwords: 198

Is 'not' a stopword? True
Is 'no' a stopword? True
Is 'never' a stopword? False

In [133]:
spam_sample = df[df['Spam'] == 1]['Text'].iloc[0]
ham_sample = df[df['Spam'] == 0]['Text'].iloc[0]

print("========== SPAM ORIGINAL ==========")
print(spam_sample)

print("\n========== SPAM WITHOUT STOPWORDS ==========")
print(remove_stopwords(spam_sample))

print("\n========== HAM ORIGINAL ==========")
print(ham_sample)

print("\n========== HAM WITHOUT STOPWORDS ==========")
print(remove_stopwords(ham_sample))

========== SPAM ORIGINAL ==========
Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

========== SPAM WITHOUT STOPWORDS ==========
Subject: naturally irresistible corporate identity lt really hard recollect company : market full suqgestions information isoverwhelminq ; good catchy logo , stylish statlonery outstanding website make task much easier . promise havinq ordered iogo company automaticaily become world ieader : isguite ciear without good products , effective business organization practicable aim hotat nowadays market ; promise marketing efforts become much effective . list clear benefits : creativeness : hand - made , original logos , specially done reflect distinctive company image . convenience : logo stationery provided formats ; easy - - use content management system letsyou change website content even structure . promptness : see logo drafts within three business days . affordability : marketing break - ' make gaps budget . 100 % satisfaction guaranteed : provide unlimited amount changes extra fees surethat love result collaboration . look portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

========== HAM ORIGINAL ==========
Subject: hello guys ,  i ' m " bugging you " for your completed questionnaire and for a one - page  bio / statement on your thoughts on " business edu and the new economy " . if  my records are incorrect please re - ship your responses to me . i want to  put everything together next week so that i can ship it back to everyone .  the questionnaire is attached as well as copies of the bio pages for  michael froehls and myself ( two somewhat different approaches ) . the idea  of the latter is just to introduce yourself to the other panelists and give  them some background on how you are approaching the issues we will discuss .  we will also provide copies to the attendees and use this material for our  personal introductions at the opening of the panel discussions .  thanks and i look forward to seeing you in two weeks .  john  - waco _ background _ mf . doc  - jmartinbiosketch . doc  - questionnaire . doc  john d . martin  carr p . collins chair in finance  finance department  baylor university  po box 98004  waco , tx 76798  254 - 710 - 4473 ( office )  254 - 710 - 1092 ( fax )  j _ martin @ baylor . edu  web : http : / / hsb . baylor . edu / html / martinj / home . html

========== HAM WITHOUT STOPWORDS ==========
Subject: hello guys , ' " bugging " completed questionnaire one - page bio / statement thoughts " business edu new economy " . records incorrect please - ship responses . want put everything together next week ship back everyone . questionnaire attached well copies bio pages michael froehls ( two somewhat different approaches ) . idea latter introduce panelists give background approaching issues discuss . also provide copies attendees use material personal introductions opening panel discussions . thanks look forward seeing two weeks . john - waco _ background _ mf . doc - jmartinbiosketch . doc - questionnaire . doc john . martin carr p . collins chair finance finance department baylor university po box 98004 waco , tx 76798 254 - 710 - 4473 ( office ) 254 - 710 - 1092 ( fax ) j _ martin @ baylor . edu web : http : / / hsb . baylor . edu / html / martinj / home . html

In [134]:
df['Text_no_stopwords'] = df['Text'].apply(remove_stopwords)

In [135]:
df[['Text', 'Text_no_stopwords', 'Spam']].head()

,Text,Text_no_stopwords,Spam
0,Subject: naturally irresistible your corporate...,Subject: naturally irresistible corporate iden...,1
1,Subject: the stock trading gunslinger fanny i...,Subject: stock trading gunslinger fanny merril...,1
2,Subject: unbelievable new homes made easy im ...,Subject: unbelievable new homes made easy im w...,1
3,Subject: 4 color printing special request add...,Subject: 4 color printing special request addi...,1
4,"Subject: do not have money , get software cds ...","Subject: money , get software cds ! software c...",1

# Stemming

In [136]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [137]:
def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

In [138]:
words = [
    "connect",
    "connected",
    "connecting",
    "connection",
    "study",
    "studies",
    "studying",
    "playing",
    "played"
]

stemmed_words = stem_tokens(words)

for original, stemmed in zip(words, stemmed_words):
    print(f"{original:15} -> {stemmed}")

connect         -> connect
connected       -> connect
connecting      -> connect
connection      -> connect
study           -> studi
studies         -> studi
studying        -> studi
playing         -> play
played          -> play

In [139]:
from nltk.tokenize import word_tokenize

sample = df['Text'].iloc[0]

tokens = word_tokenize(sample)
stemmed_tokens = stem_tokens(tokens)

print("Original tokens:")
print(tokens[:50])

print("\nStemmed tokens:")
print(stemmed_tokens[:50])

Original tokens:
['Subject', ':', 'naturally', 'irresistible', 'your', 'corporate', 'identity', 'lt', 'is', 'really', 'hard', 'to', 'recollect', 'a', 'company', ':', 'the', 'market', 'is', 'full', 'of', 'suqgestions', 'and', 'the', 'information', 'isoverwhelminq', ';', 'but', 'a', 'good', 'catchy', 'logo', ',', 'stylish', 'statlonery', 'and', 'outstanding', 'website', 'will', 'make', 'the', 'task', 'much', 'easier', '.', 'we', 'do', 'not', 'promise', 'that']

Stemmed tokens:
['subject', ':', 'natur', 'irresist', 'your', 'corpor', 'ident', 'lt', 'is', 'realli', 'hard', 'to', 'recollect', 'a', 'compani', ':', 'the', 'market', 'is', 'full', 'of', 'suqgest', 'and', 'the', 'inform', 'isoverwhelminq', ';', 'but', 'a', 'good', 'catchi', 'logo', ',', 'stylish', 'statloneri', 'and', 'outstand', 'websit', 'will', 'make', 'the', 'task', 'much', 'easier', '.', 'we', 'do', 'not', 'promis', 'that']

# Lemmatization

In [140]:
nlp = spacy.load("en_core_web_sm")

In [141]:
def lemmatize_text(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc]

In [142]:
words = [
    "connect",
    "connected",
    "connecting",
    "connection",
    "study",
    "studies",
    "studying",
    "running",
    "better"
]

text = " ".join(words)

lemmas = lemmatize_text(text)

for original, lemma in zip(words, lemmas):
    print(f"{original:15} -> {lemma}")

connect         -> connect
connected       -> connected
connecting      -> connect
connection      -> connection
study           -> study
studies         -> study
studying        -> study
running         -> run
better          -> well

In [143]:
sample = df['Text'].iloc[0]

doc = nlp(sample)

print("Original tokens:")
print([token.text for token in doc][:50])

print("\nLemmatized tokens:")
print([token.lemma_ for token in doc][:50])

Original tokens:
['Subject', ':', 'naturally', 'irresistible', 'your', 'corporate', 'identity', ' ', 'lt', 'is', 'really', 'hard', 'to', 'recollect', 'a', 'company', ':', 'the', ' ', 'market', 'is', 'full', 'of', 'suqgestions', 'and', 'the', 'information', 'isoverwhelminq', ';', 'but', 'a', 'good', ' ', 'catchy', 'logo', ',', 'stylish', 'statlonery', 'and', 'outstanding', 'website', ' ', 'will', 'make', 'the', 'task', 'much', 'easier', '.', ' ']

Lemmatized tokens:
['subject', ':', 'naturally', 'irresistible', 'your', 'corporate', 'identity', ' ', 'lt', 'be', 'really', 'hard', 'to', 'recollect', 'a', 'company', ':', 'the', ' ', 'market', 'be', 'full', 'of', 'suqgestion', 'and', 'the', 'information', 'isoverwhelminq', ';', 'but', 'a', 'good', ' ', 'catchy', 'logo', ',', 'stylish', 'statlonery', 'and', 'outstanding', 'website', ' ', 'will', 'make', 'the', 'task', 'much', 'easy', '.', ' ']

# URLs and Email Addresses

In [158]:
url_pattern = r'https?\s*:\s*/\s*/\s*(?:www\s*\.\s*)?[\w.-]+(?:\s*\.\s*[\w.-]+)+|www\s*\.\s*[\w.-]+(?:\s*\.\s*[\w.-]+)+'


def replace_urls(text):
    return re.sub(url_pattern, 'URL_TOKEN', text)

In [159]:
sample = df['Text'].iloc[0]

print("Original:")
print(sample)

print("\nURL replaced:")
print(replace_urls(sample))

Original:
Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

URL replaced:
Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

In [160]:
email_pattern = r'\b[\w.-]+\s*@\s*[\w.-]+(?:\s*\.\s*[\w.-]+)+\b'

def replace_email_addresses(text):
    return re.sub(email_pattern, 'EMAIL_TOKEN', text)

In [161]:
sample = df['Text'].iloc[10]

print("Original:")
print(sample)

print("\nEmail addresses replaced:")
print(replace_email_addresses(sample))

Original:
Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line .

Email addresses replaced:
Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line .

In [162]:
def replace_urls_and_emails(text):
    text = replace_urls(text)
    text = replace_email_addresses(text)
    return text

In [163]:
sample = df['Text'].iloc[10]
print("Original:")
print(sample)
print("\n")
print(replace_urls_and_emails(sample))

Original:
Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http : / / www . verticallv . com  message has been sent to you by realty one highrise . learn more at www . verticallv . comif you  wish to be excluded from future mailings , please reply with the word remove in  the subject line .


Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  URL_TOKEN  message has been sent to you by realty one highrise . learn more at URL_TOKEN you  wish to be excluded from future mailings , please reply with the word remove in  the subject line .