In [2]:
import sys
import os

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [3]:
import pandas as pd

from src.preprocessing import (
    tokenize_text,
    stem_tokens,
    lowercase_text,
    replace_urls,
    replace_email_addresses,
    remove_numbers,
    remove_punctuation,
    remove_stopwords,
    lemmatize_text
)

In [4]:
df = pd.read_csv("../data/emails.csv")

print("Shape:", df.shape)
print(df.head())

Shape: (5728, 2)
                                                Text  Spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
X = df["Text"].fillna("")
y = df["Spam"]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

Train: (4582,)
Test : (1146,)

In [7]:
def clean_text_a(text):
    text = lowercase_text(text)
    text = replace_urls(text)
    text = replace_email_addresses(text)
    text = remove_numbers(text)
    text = remove_punctuation(text)
    text = remove_stopwords(text)
    return text

In [8]:
X_train_clean_a = X_train.apply(clean_text_a)
X_test_clean_a = X_test.apply(clean_text_a)

In [9]:
for i in range(3):
    print("ORIGINAL:")
    print(X_train.iloc[i])

    print("\nCLEANED:")
    print(X_train_clean_a.iloc[i])

    print("\n" + "=" * 80 + "\n")

ORIGINAL:
Subject: re : a personal favor  anurag ,  i shall talk about vikas to our it people .  can you send me his resume ?  vince  " saksena , anurag " on 05 / 07 / 2001 10 : 06 : 54 am  to : " ' vkamins @ ect . enron . com ' "  cc :  subject : a personal favor  vince ,  i have left a voice mail to you and will wait to talk to you personally . my brother vikas , who is now in london , is trying to make a switch from consulting world to working for a specific firm . over last few months , i have heard of great deal about the success of enron on line business which fits well in the area of his expertise . i am wondering if you know of some one in london who he can speak to regarding career opportunities .  since i spoke to you last , a number of things have changed . recently , my manadate was broaden to include leading a charge for developing a risk management function for both the domestic and international businesses for gmac . needless to say , this is exciting albeit making the life a little more hectic than usual .  talk to you later .  anurag  952 - 857 - 6133

CLEANED:
subject personal favor anurag shall talk vikas people send resume vince saksena anurag EMAILTOKEN cc subject personal favor vince left voice mail wait talk personally brother vikas london trying make switch consulting world working specific firm last months heard great deal success enron line business fits well area expertise wondering know one london speak regarding career opportunities since spoke last number things changed recently manadate broaden include leading charge developing risk management function domestic international businesses gmac needless say exciting albeit making life little hectic usual talk later anurag

================================================================================

ORIGINAL:
Subject: site license for power world  gentlemen ,  i recommend that we purchase this package and split the cost 3 ways between 3  power trading desks .  i think that we should go for option 3 ( ~ $ 15 , 000 ) .  lance cunningham in my group looked at this software package and found it  very useful for modeling transmission problems .  please , feel free to ask him for technical details in support of this  recommendation .  vince  - - - - - - - - - - - - - - - - - - - - - - forwarded by vince j kaminski / hou / ect on 11 / 10 / 2000  09 : 17 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  lance cunningham @ enron on 11 / 09 / 2000 06 : 15 : 14 pm  to : vince j kaminski / hou / ect @ ect  cc : vasant shanbhogue / hou / ect @ ect  subject : site license for power world  vince ,  we have three options to increase our availability across enron for the power  world load flow software .  option 1 , upgrade to a site license for the load flow software only . price  $ 9 , 990 . 00  this would give all of enron the ability to perform load flows , but not  determine marginal cost or available transfer capacity ( atc ) because only the  optimal power flow ( opf ) version can perform that task .  option 2 , site license for the load flow and purchase 1 opf package for  walter coffer ' s group . price $ 11 , 240 .  this would give all of enron the ability to perform load flows and one other  group the ability to determine marginal cost and atc .  option 3 , site license for load flows , opf and atc . price $ 14 , 990 . 00  this would give all of enron the ability to perform load flows , marginal  cost , and atc .  regards ,  lance

CLEANED:
subject site license power world gentlemen recommend purchase package split cost ways power trading desks think go option lance cunningham group looked software package found useful modeling transmission problems please feel free ask technical details support recommendation vince forwarded vince j kaminski hou ect lance cunningham enron pm vince j kaminski hou ect ect cc vasant shanbhogue hou ect ect subject site license power world vince three options increase availability across enron power world load flow software option upgrade site license load flow software price would give enron ability perform load flows determine marginal cost available transfer capacity atc optimal power flow opf version perform task option site license load flow purchase opf package walter coffer group price would give enron ability perform load flows one group ability determine marginal cost atc option site license load flows opf atc price would give enron ability perform load flows marginal cost atc regards lance

================================================================================

ORIGINAL:
Subject: would you like a $ 250 gas card ?  don ' t let the current high price of gas get to you .  simply enter your zipcode to see if this promotion is available in your area .  ubycvski

CLEANED:
subject would like gas card let current high price gas get simply enter zipcode see promotion available area ubycvski

================================================================================

In [10]:
sample = """
Congratulations! Visit http : / / www . example . com
or contact test @ example . com today! You won 1000 dollars!!!
"""

print("Original:")
print(sample)

print("\nCleaned:")
print(clean_text_a(sample))

Original:

Congratulations! Visit http : / / www . example . com
or contact test @ example . com today! You won 1000 dollars!!!


Cleaned:
congratulations visit URLTOKEN contact EMAILTOKEN today dollars

In [11]:
print("Training samples:", len(X_train_clean_a))
print("Testing samples :", len(X_test_clean_a))

print("Missing train:", X_train_clean_a.isna().sum())
print("Missing test :", X_test_clean_a.isna().sum())

Training samples: 4582
Testing samples : 1146
Missing train: 0
Missing test : 0

In [12]:
def clean_text_b(text):
    text = clean_text_a(text)

    tokens = tokenize_text(text)
    tokens = stem_tokens(tokens)

    return " ".join(tokens)

In [13]:
X_train_clean_b = X_train.apply(clean_text_b)
X_test_clean_b = X_test.apply(clean_text_b)

In [14]:
for i in range(3):
    print("ORIGINAL:")
    print(X_train.iloc[i])

    print("\nCLEAN A:")
    print(X_train_clean_a.iloc[i])

    print("\nCLEAN B - STEMMED:")
    print(X_train_clean_b.iloc[i])

    print("\n" + "="*80 + "\n")

ORIGINAL:
Subject: re : a personal favor  anurag ,  i shall talk about vikas to our it people .  can you send me his resume ?  vince  " saksena , anurag " on 05 / 07 / 2001 10 : 06 : 54 am  to : " ' vkamins @ ect . enron . com ' "  cc :  subject : a personal favor  vince ,  i have left a voice mail to you and will wait to talk to you personally . my brother vikas , who is now in london , is trying to make a switch from consulting world to working for a specific firm . over last few months , i have heard of great deal about the success of enron on line business which fits well in the area of his expertise . i am wondering if you know of some one in london who he can speak to regarding career opportunities .  since i spoke to you last , a number of things have changed . recently , my manadate was broaden to include leading a charge for developing a risk management function for both the domestic and international businesses for gmac . needless to say , this is exciting albeit making the life a little more hectic than usual .  talk to you later .  anurag  952 - 857 - 6133

CLEAN A:
subject personal favor anurag shall talk vikas people send resume vince saksena anurag EMAILTOKEN cc subject personal favor vince left voice mail wait talk personally brother vikas london trying make switch consulting world working specific firm last months heard great deal success enron line business fits well area expertise wondering know one london speak regarding career opportunities since spoke last number things changed recently manadate broaden include leading charge developing risk management function domestic international businesses gmac needless say exciting albeit making life little hectic usual talk later anurag

CLEAN B - STEMMED:
subject person favor anurag shall talk vika peopl send resum vinc saksena anurag emailtoken cc subject person favor vinc left voic mail wait talk person brother vika london tri make switch consult world work specif firm last month heard great deal success enron line busi fit well area expertis wonder know one london speak regard career opportun sinc spoke last number thing chang recent manad broaden includ lead charg develop risk manag function domest intern busi gmac needless say excit albeit make life littl hectic usual talk later anurag

================================================================================

ORIGINAL:
Subject: site license for power world  gentlemen ,  i recommend that we purchase this package and split the cost 3 ways between 3  power trading desks .  i think that we should go for option 3 ( ~ $ 15 , 000 ) .  lance cunningham in my group looked at this software package and found it  very useful for modeling transmission problems .  please , feel free to ask him for technical details in support of this  recommendation .  vince  - - - - - - - - - - - - - - - - - - - - - - forwarded by vince j kaminski / hou / ect on 11 / 10 / 2000  09 : 17 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  lance cunningham @ enron on 11 / 09 / 2000 06 : 15 : 14 pm  to : vince j kaminski / hou / ect @ ect  cc : vasant shanbhogue / hou / ect @ ect  subject : site license for power world  vince ,  we have three options to increase our availability across enron for the power  world load flow software .  option 1 , upgrade to a site license for the load flow software only . price  $ 9 , 990 . 00  this would give all of enron the ability to perform load flows , but not  determine marginal cost or available transfer capacity ( atc ) because only the  optimal power flow ( opf ) version can perform that task .  option 2 , site license for the load flow and purchase 1 opf package for  walter coffer ' s group . price $ 11 , 240 .  this would give all of enron the ability to perform load flows and one other  group the ability to determine marginal cost and atc .  option 3 , site license for load flows , opf and atc . price $ 14 , 990 . 00  this would give all of enron the ability to perform load flows , marginal  cost , and atc .  regards ,  lance

CLEAN A:
subject site license power world gentlemen recommend purchase package split cost ways power trading desks think go option lance cunningham group looked software package found useful modeling transmission problems please feel free ask technical details support recommendation vince forwarded vince j kaminski hou ect lance cunningham enron pm vince j kaminski hou ect ect cc vasant shanbhogue hou ect ect subject site license power world vince three options increase availability across enron power world load flow software option upgrade site license load flow software price would give enron ability perform load flows determine marginal cost available transfer capacity atc optimal power flow opf version perform task option site license load flow purchase opf package walter coffer group price would give enron ability perform load flows one group ability determine marginal cost atc option site license load flows opf atc price would give enron ability perform load flows marginal cost atc regards lance

CLEAN B - STEMMED:
subject site licens power world gentlemen recommend purchas packag split cost way power trade desk think go option lanc cunningham group look softwar packag found use model transmiss problem pleas feel free ask technic detail support recommend vinc forward vinc j kaminski hou ect lanc cunningham enron pm vinc j kaminski hou ect ect cc vasant shanbhogu hou ect ect subject site licens power world vinc three option increas avail across enron power world load flow softwar option upgrad site licens load flow softwar price would give enron abil perform load flow determin margin cost avail transfer capac atc optim power flow opf version perform task option site licens load flow purchas opf packag walter coffer group price would give enron abil perform load flow one group abil determin margin cost atc option site licens load flow opf atc price would give enron abil perform load flow margin cost atc regard lanc

================================================================================

ORIGINAL:
Subject: would you like a $ 250 gas card ?  don ' t let the current high price of gas get to you .  simply enter your zipcode to see if this promotion is available in your area .  ubycvski

CLEAN A:
subject would like gas card let current high price gas get simply enter zipcode see promotion available area ubycvski

CLEAN B - STEMMED:
subject would like ga card let current high price ga get simpli enter zipcod see promot avail area ubycvski

================================================================================

In [15]:
print("Training samples:", len(X_train_clean_b))
print("Testing samples :", len(X_test_clean_b))

print("Missing train:", X_train_clean_b.isna().sum())
print("Missing test :", X_test_clean_b.isna().sum())

Training samples: 4582
Testing samples : 1146
Missing train: 0
Missing test : 0

In [16]:
def clean_text_c(text):
    text = clean_text_a(text)

    tokens = lemmatize_text(text)

    return " ".join(tokens)

In [17]:
X_train_clean_c = X_train.apply(clean_text_c)
X_test_clean_c = X_test.apply(clean_text_c)

In [18]:
for i in range(3):
    print("ORIGINAL:")
    print(X_train.iloc[i])

    print("\nCLEAN A:")
    print(X_train_clean_a.iloc[i])

    print("\nCLEAN B - STEMMING:")
    print(X_train_clean_b.iloc[i])

    print("\nCLEAN C - LEMMATIZATION:")
    print(X_train_clean_c.iloc[i])

    print("\n" + "="*80 + "\n")

ORIGINAL:
Subject: re : a personal favor  anurag ,  i shall talk about vikas to our it people .  can you send me his resume ?  vince  " saksena , anurag " on 05 / 07 / 2001 10 : 06 : 54 am  to : " ' vkamins @ ect . enron . com ' "  cc :  subject : a personal favor  vince ,  i have left a voice mail to you and will wait to talk to you personally . my brother vikas , who is now in london , is trying to make a switch from consulting world to working for a specific firm . over last few months , i have heard of great deal about the success of enron on line business which fits well in the area of his expertise . i am wondering if you know of some one in london who he can speak to regarding career opportunities .  since i spoke to you last , a number of things have changed . recently , my manadate was broaden to include leading a charge for developing a risk management function for both the domestic and international businesses for gmac . needless to say , this is exciting albeit making the life a little more hectic than usual .  talk to you later .  anurag  952 - 857 - 6133

CLEAN A:
subject personal favor anurag shall talk vikas people send resume vince saksena anurag EMAILTOKEN cc subject personal favor vince left voice mail wait talk personally brother vikas london trying make switch consulting world working specific firm last months heard great deal success enron line business fits well area expertise wondering know one london speak regarding career opportunities since spoke last number things changed recently manadate broaden include leading charge developing risk management function domestic international businesses gmac needless say exciting albeit making life little hectic usual talk later anurag

CLEAN B - STEMMING:
subject person favor anurag shall talk vika peopl send resum vinc saksena anurag emailtoken cc subject person favor vinc left voic mail wait talk person brother vika london tri make switch consult world work specif firm last month heard great deal success enron line busi fit well area expertis wonder know one london speak regard career opportun sinc spoke last number thing chang recent manad broaden includ lead charg develop risk manag function domest intern busi gmac needless say excit albeit make life littl hectic usual talk later anurag

CLEAN C - LEMMATIZATION:
subject personal favor anurag shall talk vikas people send resume vince saksena anurag EMAILTOKEN cc subject personal favor vince leave voice mail wait talk personally brother vikas london try make switch consult world work specific firm last month hear great deal success enron line business fit well area expertise wonder know one london speak regard career opportunity since speak last number thing change recently manadate broaden include lead charge develop risk management function domestic international business gmac needless say exciting albeit make life little hectic usual talk later anurag

================================================================================

ORIGINAL:
Subject: site license for power world  gentlemen ,  i recommend that we purchase this package and split the cost 3 ways between 3  power trading desks .  i think that we should go for option 3 ( ~ $ 15 , 000 ) .  lance cunningham in my group looked at this software package and found it  very useful for modeling transmission problems .  please , feel free to ask him for technical details in support of this  recommendation .  vince  - - - - - - - - - - - - - - - - - - - - - - forwarded by vince j kaminski / hou / ect on 11 / 10 / 2000  09 : 17 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  lance cunningham @ enron on 11 / 09 / 2000 06 : 15 : 14 pm  to : vince j kaminski / hou / ect @ ect  cc : vasant shanbhogue / hou / ect @ ect  subject : site license for power world  vince ,  we have three options to increase our availability across enron for the power  world load flow software .  option 1 , upgrade to a site license for the load flow software only . price  $ 9 , 990 . 00  this would give all of enron the ability to perform load flows , but not  determine marginal cost or available transfer capacity ( atc ) because only the  optimal power flow ( opf ) version can perform that task .  option 2 , site license for the load flow and purchase 1 opf package for  walter coffer ' s group . price $ 11 , 240 .  this would give all of enron the ability to perform load flows and one other  group the ability to determine marginal cost and atc .  option 3 , site license for load flows , opf and atc . price $ 14 , 990 . 00  this would give all of enron the ability to perform load flows , marginal  cost , and atc .  regards ,  lance

CLEAN A:
subject site license power world gentlemen recommend purchase package split cost ways power trading desks think go option lance cunningham group looked software package found useful modeling transmission problems please feel free ask technical details support recommendation vince forwarded vince j kaminski hou ect lance cunningham enron pm vince j kaminski hou ect ect cc vasant shanbhogue hou ect ect subject site license power world vince three options increase availability across enron power world load flow software option upgrade site license load flow software price would give enron ability perform load flows determine marginal cost available transfer capacity atc optimal power flow opf version perform task option site license load flow purchase opf package walter coffer group price would give enron ability perform load flows one group ability determine marginal cost atc option site license load flows opf atc price would give enron ability perform load flows marginal cost atc regards lance

CLEAN B - STEMMING:
subject site licens power world gentlemen recommend purchas packag split cost way power trade desk think go option lanc cunningham group look softwar packag found use model transmiss problem pleas feel free ask technic detail support recommend vinc forward vinc j kaminski hou ect lanc cunningham enron pm vinc j kaminski hou ect ect cc vasant shanbhogu hou ect ect subject site licens power world vinc three option increas avail across enron power world load flow softwar option upgrad site licens load flow softwar price would give enron abil perform load flow determin margin cost avail transfer capac atc optim power flow opf version perform task option site licens load flow purchas opf packag walter coffer group price would give enron abil perform load flow one group abil determin margin cost atc option site licens load flow opf atc price would give enron abil perform load flow margin cost atc regard lanc

CLEAN C - LEMMATIZATION:
subject site license power world gentleman recommend purchase package split cost way power trading desk think go option lance cunningham group look software package find useful modeling transmission problem please feel free ask technical detail support recommendation vince forward vince j kaminski hou ect lance cunningham enron pm vince j kaminski hou ect ect cc vasant shanbhogue hou ect ect subject site license power world vince three option increase availability across enron power world load flow software option upgrade site license load flow software price would give enron ability perform load flow determine marginal cost available transfer capacity atc optimal power flow opf version perform task option site license load flow purchase opf package walter coffer group price would give enron ability perform load flow one group ability determine marginal cost atc option site license load flow opf atc price would give enron ability perform load flow marginal cost atc regard lance

================================================================================

ORIGINAL:
Subject: would you like a $ 250 gas card ?  don ' t let the current high price of gas get to you .  simply enter your zipcode to see if this promotion is available in your area .  ubycvski

CLEAN A:
subject would like gas card let current high price gas get simply enter zipcode see promotion available area ubycvski

CLEAN B - STEMMING:
subject would like ga card let current high price ga get simpli enter zipcod see promot avail area ubycvski

CLEAN C - LEMMATIZATION:
subject would like gas card let current high price gas get simply enter zipcode see promotion available area ubycvski

================================================================================

In [19]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [20]:
def create_bow_features(X_train, X_test):
    vectorizer = CountVectorizer()

    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    return X_train_vec, X_test_vec, vectorizer

In [21]:
def create_binary_bow_features(X_train, X_test):
    vectorizer = CountVectorizer(binary=True)

    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    return X_train_vec, X_test_vec, vectorizer

In [22]:
def create_tfidf_features(X_train, X_test):
    vectorizer = TfidfVectorizer()

    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    return X_train_vec, X_test_vec, vectorizer

In [23]:
X_train_a_bow, X_test_a_bow, bow_a_vectorizer = create_bow_features(
    X_train_clean_a,
    X_test_clean_a
)

print("BoW")
print("Train:", X_train_a_bow.shape)
print("Test :", X_test_a_bow.shape)
print("Vocab:", len(bow_a_vectorizer.vocabulary_))

BoW
Train: (4582, 29119)
Test : (1146, 29119)
Vocab: 29119

In [24]:
X_train_a_binary, X_test_a_binary, binary_a_vectorizer = create_binary_bow_features(
    X_train_clean_a,
    X_test_clean_a
)

print("Binary BoW")
print("Train:", X_train_a_binary.shape)
print("Test :", X_test_a_binary.shape)
print("Vocab:", len(binary_a_vectorizer.vocabulary_))

Binary BoW
Train: (4582, 29119)
Test : (1146, 29119)
Vocab: 29119

In [25]:
X_train_a_tfidf, X_test_a_tfidf, tfidf_a_vectorizer = create_tfidf_features(
    X_train_clean_a,
    X_test_clean_a
)

print("TF-IDF")
print("Train:", X_train_a_tfidf.shape)
print("Test :", X_test_a_tfidf.shape)
print("Vocab:", len(tfidf_a_vectorizer.vocabulary_))

TF-IDF
Train: (4582, 29119)
Test : (1146, 29119)
Vocab: 29119

In [26]:
X_train_b_bow, X_test_b_bow, bow_b_vectorizer = create_bow_features(
    X_train_clean_b,
    X_test_clean_b
)

X_train_b_binary, X_test_b_binary, binary_b_vectorizer = create_binary_bow_features(
    X_train_clean_b,
    X_test_clean_b
)

X_train_b_tfidf, X_test_b_tfidf, tfidf_b_vectorizer = create_tfidf_features(
    X_train_clean_b,
    X_test_clean_b
)

In [27]:
print("Clean B - BoW     :", X_train_b_bow.shape)
print("Clean B - Binary  :", X_train_b_binary.shape)
print("Clean B - TF-IDF  :", X_train_b_tfidf.shape)

Clean B - BoW     : (4582, 21894)
Clean B - Binary  : (4582, 21894)
Clean B - TF-IDF  : (4582, 21894)

In [28]:
X_train_c_bow, X_test_c_bow, bow_c_vectorizer = create_bow_features(
    X_train_clean_c,
    X_test_clean_c
)

X_train_c_binary, X_test_c_binary, binary_c_vectorizer = create_binary_bow_features(
    X_train_clean_c,
    X_test_clean_c
)

X_train_c_tfidf, X_test_c_tfidf, tfidf_c_vectorizer = create_tfidf_features(
    X_train_clean_c,
    X_test_clean_c
)

In [29]:
print("Clean C - BoW     :", X_train_c_bow.shape)
print("Clean C - Binary  :", X_train_c_binary.shape)
print("Clean C - TF-IDF  :", X_train_c_tfidf.shape)

Clean C - BoW     : (4582, 25341)
Clean C - Binary  : (4582, 25341)
Clean C - TF-IDF  : (4582, 25341)

In [30]:
def create_word_ngram_features(X_train, X_test, ngram_range=(1, 2)):
    vectorizer = TfidfVectorizer(
        ngram_range=ngram_range
    )

    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    return X_train_vec, X_test_vec, vectorizer

In [31]:
X_train_a_ngram, X_test_a_ngram, ngram_a_vectorizer = create_word_ngram_features(
    X_train_clean_a,
    X_test_clean_a,
    ngram_range=(1, 2)
)

print("Clean A - 1 to 2 grams")
print("Train:", X_train_a_ngram.shape)
print("Test :", X_test_a_ngram.shape)
print("Vocab:", len(ngram_a_vectorizer.vocabulary_))

Clean A - 1 to 2 grams
Train: (4582, 307127)
Test : (1146, 307127)
Vocab: 307127

In [32]:
X_train_a_ngram3, X_test_a_ngram3, ngram3_a_vectorizer = create_word_ngram_features(
    X_train_clean_a,
    X_test_clean_a,
    ngram_range=(1, 3)
)

print("Clean A - 1 to 3 grams")
print("Train:", X_train_a_ngram3.shape)
print("Test :", X_test_a_ngram3.shape)
print("Vocab:", len(ngram3_a_vectorizer.vocabulary_))

Clean A - 1 to 3 grams
Train: (4582, 678493)
Test : (1146, 678493)
Vocab: 678493

# Clean A + BoW + MultinomialNB

In [33]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train_a_bow, y_train)

y_pred_a_bow_nb = nb_model.predict(X_test_a_bow)

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,classification_report

In [37]:

accuracy = accuracy_score(y_test, y_pred_a_bow_nb)
precision = precision_score(y_test, y_pred_a_bow_nb)
recall = recall_score(y_test, y_pred_a_bow_nb)
f1 = f1_score(y_test, y_pred_a_bow_nb)

print("Clean A + BoW + MultinomialNB")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Clean A + BoW + MultinomialNB
Accuracy : 0.9904013961605584
Precision: 0.9713261648745519
Recall   : 0.9890510948905109
F1 Score : 0.9801084990958409

In [38]:
print(classification_report(
    y_test,
    y_pred_a_bow_nb,
    target_names=["HAM", "SPAM"]
))

              precision    recall  f1-score   support

         HAM       1.00      0.99      0.99       872
        SPAM       0.97      0.99      0.98       274

    accuracy                           0.99      1146
   macro avg       0.98      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146

In [39]:
results = []

results.append({
    "Preprocessing": "Clean A",
    "Vectorizer": "BoW",
    "Model": "MultinomialNB",
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1": f1
})

results_df = pd.DataFrame(results)

results_df

,Preprocessing,Vectorizer,Model,Accuracy,Precision,Recall,F1
0,Clean A,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108

# Clean A + Binary BoW + MultinomialNB

In [40]:
nb_binary_model = MultinomialNB()

nb_binary_model.fit(X_train_a_binary, y_train)

y_pred_a_binary_nb = nb_binary_model.predict(X_test_a_binary)

In [41]:
print("Clean A + Binary BoW + MultinomialNB")

print("Accuracy :", accuracy_score(y_test, y_pred_a_binary_nb))
print("Precision:", precision_score(y_test, y_pred_a_binary_nb))
print("Recall   :", recall_score(y_test, y_pred_a_binary_nb))
print("F1 Score :", f1_score(y_test, y_pred_a_binary_nb))

Clean A + Binary BoW + MultinomialNB
Accuracy : 0.9930191972076788
Precision: 0.9889705882352942
Recall   : 0.9817518248175182
F1 Score : 0.9853479853479854

In [42]:
results.append({
    "Preprocessing": "Clean A",
    "Vectorizer": "Binary BoW",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_a_binary_nb),
    "Precision": precision_score(y_test, y_pred_a_binary_nb),
    "Recall": recall_score(y_test, y_pred_a_binary_nb),
    "F1": f1_score(y_test, y_pred_a_binary_nb)
})

results_df = pd.DataFrame(results)
results_df

,Preprocessing,Vectorizer,Model,Accuracy,Precision,Recall,F1
0,Clean A,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108
1,Clean A,Binary BoW,MultinomialNB,0.993019,0.988971,0.981752,0.985348

# Clean A + TF-IDF + MultinomialNB

In [43]:
nb_tfidf_model = MultinomialNB()

nb_tfidf_model.fit(X_train_a_tfidf, y_train)

y_pred_a_tfidf_nb = nb_tfidf_model.predict(X_test_a_tfidf)

In [44]:
print("Clean A + TF-IDF + MultinomialNB")

print("Accuracy :", accuracy_score(y_test, y_pred_a_tfidf_nb))
print("Precision:", precision_score(y_test, y_pred_a_tfidf_nb))
print("Recall   :", recall_score(y_test, y_pred_a_tfidf_nb))
print("F1 Score :", f1_score(y_test, y_pred_a_tfidf_nb))

Clean A + TF-IDF + MultinomialNB
Accuracy : 0.9022687609075044
Precision: 1.0
Recall   : 0.5912408759124088
F1 Score : 0.7431192660550459

In [45]:
results.append({
    "Preprocessing": "Clean A",
    "Vectorizer": "TF-IDF",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_a_tfidf_nb),
    "Precision": precision_score(y_test, y_pred_a_tfidf_nb),
    "Recall": recall_score(y_test, y_pred_a_tfidf_nb),
    "F1": f1_score(y_test, y_pred_a_tfidf_nb)
})

results_df = pd.DataFrame(results)

results_df

,Preprocessing,Vectorizer,Model,Accuracy,Precision,Recall,F1
0,Clean A,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108
1,Clean A,Binary BoW,MultinomialNB,0.993019,0.988971,0.981752,0.985348
2,Clean A,TF-IDF,MultinomialNB,0.902269,1.000000,0.591241,0.743119

# Clean B + BoW + MultinomialNB

In [46]:
nb_b_bow_model = MultinomialNB()

nb_b_bow_model.fit(X_train_b_bow, y_train)

y_pred_b_bow_nb = nb_b_bow_model.predict(X_test_b_bow)

In [47]:
print("Clean B + BoW + MultinomialNB")

print("Accuracy :", accuracy_score(y_test, y_pred_b_bow_nb))
print("Precision:", precision_score(y_test, y_pred_b_bow_nb))
print("Recall   :", recall_score(y_test, y_pred_b_bow_nb))
print("F1 Score :", f1_score(y_test, y_pred_b_bow_nb))

Clean B + BoW + MultinomialNB
Accuracy : 0.9904013961605584
Precision: 0.9713261648745519
Recall   : 0.9890510948905109
F1 Score : 0.9801084990958409

In [48]:
results.append({
    "Preprocessing": "Clean B",
    "Vectorizer": "BoW",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_b_bow_nb),
    "Precision": precision_score(y_test, y_pred_b_bow_nb),
    "Recall": recall_score(y_test, y_pred_b_bow_nb),
    "F1": f1_score(y_test, y_pred_b_bow_nb)
})

results_df = pd.DataFrame(results)

results_df

,Preprocessing,Vectorizer,Model,Accuracy,Precision,Recall,F1
0,Clean A,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108
1,Clean A,Binary BoW,MultinomialNB,0.993019,0.988971,0.981752,0.985348
2,Clean A,TF-IDF,MultinomialNB,0.902269,1.000000,0.591241,0.743119
3,Clean B,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108

# Clean B + Binary BoW + MultinomialNB

In [49]:
nb_b_binary_model = MultinomialNB()

nb_b_binary_model.fit(X_train_b_binary, y_train)

y_pred_b_binary_nb = nb_b_binary_model.predict(X_test_b_binary)

In [50]:
print("Clean B + Binary BoW + MultinomialNB")

print("Accuracy :", accuracy_score(y_test, y_pred_b_binary_nb))
print("Precision:", precision_score(y_test, y_pred_b_binary_nb))
print("Recall   :", recall_score(y_test, y_pred_b_binary_nb))
print("F1 Score :", f1_score(y_test, y_pred_b_binary_nb))

Clean B + Binary BoW + MultinomialNB
Accuracy : 0.9904013961605584
Precision: 0.985239852398524
Recall   : 0.9744525547445255
F1 Score : 0.9798165137614679

# Clean C + BoW + MultinomialNB

In [51]:
nb_c_bow_model = MultinomialNB()

nb_c_bow_model.fit(X_train_c_bow, y_train)

y_pred_c_bow_nb = nb_c_bow_model.predict(X_test_c_bow)

print("Clean C + BoW + MultinomialNB")
print("Accuracy :", accuracy_score(y_test, y_pred_c_bow_nb))
print("Precision:", precision_score(y_test, y_pred_c_bow_nb))
print("Recall   :", recall_score(y_test, y_pred_c_bow_nb))
print("F1 Score :", f1_score(y_test, y_pred_c_bow_nb))

Clean C + BoW + MultinomialNB
Accuracy : 0.9895287958115183
Precision: 0.9712230215827338
Recall   : 0.9854014598540146
F1 Score : 0.9782608695652174

In [52]:
nb_c_binary_model = MultinomialNB()

nb_c_binary_model.fit(X_train_c_binary, y_train)

y_pred_c_binary_nb = nb_c_binary_model.predict(X_test_c_binary)

print("Clean C + Binary BoW + MultinomialNB")
print("Accuracy :", accuracy_score(y_test, y_pred_c_binary_nb))
print("Precision:", precision_score(y_test, y_pred_c_binary_nb))
print("Recall   :", recall_score(y_test, y_pred_c_binary_nb))
print("F1 Score :", f1_score(y_test, y_pred_c_binary_nb))

Clean C + Binary BoW + MultinomialNB
Accuracy : 0.9904013961605584
Precision: 0.985239852398524
Recall   : 0.9744525547445255
F1 Score : 0.9798165137614679

In [53]:
nb_c_tfidf_model = MultinomialNB()

nb_c_tfidf_model.fit(X_train_c_tfidf, y_train)

y_pred_c_tfidf_nb = nb_c_tfidf_model.predict(X_test_c_tfidf)

print("Clean C + TF-IDF + MultinomialNB")
print("Accuracy :", accuracy_score(y_test, y_pred_c_tfidf_nb))
print("Precision:", precision_score(y_test, y_pred_c_tfidf_nb))
print("Recall   :", recall_score(y_test, y_pred_c_tfidf_nb))
print("F1 Score :", f1_score(y_test, y_pred_c_tfidf_nb))

Clean C + TF-IDF + MultinomialNB
Accuracy : 0.8996509598603839
Precision: 1.0
Recall   : 0.5802919708029197
F1 Score : 0.7344110854503464

In [54]:
results.append({
    "Preprocessing": "Clean C",
    "Vectorizer": "BoW",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_c_bow_nb),
    "Precision": precision_score(y_test, y_pred_c_bow_nb),
    "Recall": recall_score(y_test, y_pred_c_bow_nb),
    "F1": f1_score(y_test, y_pred_c_bow_nb)
})

results.append({
    "Preprocessing": "Clean C",
    "Vectorizer": "Binary BoW",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_c_binary_nb),
    "Precision": precision_score(y_test, y_pred_c_binary_nb),
    "Recall": recall_score(y_test, y_pred_c_binary_nb),
    "F1": f1_score(y_test, y_pred_c_binary_nb)
})

results.append({
    "Preprocessing": "Clean C",
    "Vectorizer": "TF-IDF",
    "Model": "MultinomialNB",
    "Accuracy": accuracy_score(y_test, y_pred_c_tfidf_nb),
    "Precision": precision_score(y_test, y_pred_c_tfidf_nb),
    "Recall": recall_score(y_test, y_pred_c_tfidf_nb),
    "F1": f1_score(y_test, y_pred_c_tfidf_nb)
})

In [55]:
results_df = pd.DataFrame(results)
results_df

,Preprocessing,Vectorizer,Model,Accuracy,Precision,Recall,F1
0,Clean A,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108
1,Clean A,Binary BoW,MultinomialNB,0.993019,0.988971,0.981752,0.985348
2,Clean A,TF-IDF,MultinomialNB,0.902269,1.000000,0.591241,0.743119
3,Clean B,BoW,MultinomialNB,0.990401,0.971326,0.989051,0.980108
4,Clean C,BoW,MultinomialNB,0.989529,0.971223,0.985401,0.978261
5,Clean C,Binary BoW,MultinomialNB,0.990401,0.985240,0.974453,0.979817
6,Clean C,TF-IDF,MultinomialNB,0.899651,1.000000,0.580292,0.734411